apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: rancher.io/hostpath
parameters:
  type: pd-standard
reclaimPolicy: Delete
volumeBindingMode: Immediate
