apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: screenshot-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: screenshot-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: cpu
      target:
        type: AverageValue
        averageValue: 70m
  - type: Pods
    pods:
      metric:
        name: memory
      target:
        type: AverageValue
        averageValue: 80Mi
