apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: screenshot-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - screenshot-app.local
    secretName: ca-key-pair #screenshot-tls
  rules:
  - host: screenshot-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: screenshot-app
            port:
              number: 80