apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: screenshot-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - screenshots.example.com
    secretName: screenshot-tls
  rules:
  - host: screenshots.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: screenshot-app
            port:
              number: 80